"""empty message

Revision ID: 009311cb2012
Revises: 0bb59896bf1f
Create Date: 2024-06-17 00:22:36.176495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009311cb2012'
down_revision: Union[str, None] = '0bb59896bf1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authorized', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'authorized')
    # ### end Alembic commands ###
